### ISSUE TITLE
Ignore .DS_Store files

### ISSUE THREAD

**Issue by Albert221** [leancodepl/flutter_webp#11]
```
Error (Xcode): Target release_ios_bundle_flutter_assets failed: Error: User-defined transformation of asset "/Users/albert/Projects/xx/yy/packages/zz/assets/images/illustrations/.DS_Store" failed.
```

While having:

```yaml
flutter:
  assets:
    - path: assets/images/illustrations/
      transformers:
        - package: webp
          args: ["--lossless"]
```
